name: Build

on:
  push:
    branches:
      - test_timeout_gradle_daemon
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_and_apk:
    name: "Local tests and APKs"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      security-events: write

    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check spotless
        run: |
          # Define paths
          STACK_TRACE_FILE="gradle-x-stack-trace.txt"
          GRADLE_BUILD_LOG="gradle-x-build.log"

          ./gradlew assembleDebug > $GRADLE_BUILD_LOG 2>&1 &
          GRADLE_PID=$!

          (
          while kill -0 $GRADLE_PID 2>/dev/null; do
          sleep 5 # Adjust interval as needed
          done
          # Gradle process is about to terminate; generate stack trace
          echo "Gradle process is terminating. Capturing stack trace..."
          jstack -l $GRADLE_PID > $STACK_TRACE_FILE || echo "Failed to capture stack trace"
          ) &

          wait $GRADLE_PID || echo "Gradle build exited with non-zero status"

          if [ ! -f $STACK_TRACE_FILE ]; then
          echo "Gradle did not terminate cleanly; no stack trace captured."
          fi
        continue-on-error: true

      - name: Upload Gradle Daemon Logs
        if: always() # Ensure this step runs even if the build fails or times out
        uses: actions/upload-artifact@v3
        with:
            name: gradle-daemon-logs
            path: gradle-x*
